### ISSUE TITLE
.env file is publicly exposed

### ISSUE THREAD

**Issue by Aditya-Ghosh-27** [AnindoChoudhury/TodoApp#2]
Steps to solve this issue

1. Git clone this repo
2. Go to frontend folder
3. Delete the .env file
4. Push again

**Comment by Aditya-Ghosh-27** [comment]
Steps to solve this issue 

1. Git clone this repo
2. Go to frontend folder
3. Delete the .env file 
4. Push again

**Comment by AnindoChoudhury** [comment]
Thank you for checking it out!
